language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS dbtest;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -p dbtest < ./examples/dbtest.sql -uroot; fi

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: false
